---
project_name: varnish-cache-invalidator
env:
  - CGO_ENABLED=0
  - GOFLAGS=-mod=vendor
  - GO111MODULE=auto
before:
  hooks:
    - go mod vendor
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
archives:
  - replacements:
      amd64: x86_64
builds:
  - id: binary
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w
    main: ./cmd/varnish-cache-invalidator/main.go
