---
project_name: varnish-cache-invalidator

env:
  - CGO_ENABLED=0
  - GO111MODULE=auto

before:
  hooks:
    - go mod tidy
    - go mod download

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^build:'
      - 'README'
      - '^Merge branch'
      - '^Merge pull request'

archives:
  - replacements:
      amd64: x86_64

builds:
  - id: binary
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    binary: varnish-cache-invalidator
    ldflags:
      - -s -w -X github.com/bilalcaliskan/varnish-cache-invalidator/cmd.GitVersion={{ .Version }} -X github.com/bilalcaliskan/varnish-cache-invalidator/cmd.gitCommit={{ .ShortCommit }}  -X github.com/bilalcaliskan/varnish-cache-invalidator/cmd.buildDate={{ .CommitDate }}
    main: ./main.go

release:
  github:
    owner: bilalcaliskan
    name: varnish-cache-invalidator

dockers:
  - image_templates:
      - "docker.io/bilalcaliskan/{{ .ProjectName }}:{{ .Version }}"
      - "docker.io/bilalcaliskan/{{ .ProjectName }}:latest"
    dockerfile: Dockerfile.goreleaser
    goos: linux
    goarch: amd64
    use: docker
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/bilalcaliskan/varnish-cache-invalidator
      - --label=org.opencontainers.image.source=https://github.com/bilalcaliskan/varnish-cache-invalidator
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache
