---

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - nginx_deployment.yaml
  - nginx_service.yaml

configMapGenerator:
  - name: varnish-config
    files:
      - default.vcl
