---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: varnish-cache-invalidator
  name: varnish-cache-invalidator
spec:
  ports:
    - name: 3000-tcp
      port: 3000
      protocol: TCP
      targetPort: 3000
    - name: 3001-tcp
      port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app: varnish-cache-invalidator
    deployment: varnish-cache-invalidator
  sessionAffinity: None
  type: NodePort
